import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Head from "next/head";
import {Meta} from "next/dist/lib/metadata/generate/meta";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>
) {
    return (
        <html lang="en">
        <Head>
            <Meta name="viewport" content="initial-scale=1, width=device-width" />
        </Head>
        <body>
        {children}
        </body>
        </html>
    );
}
